# Generated by Django 2.0.2 on 2018-04-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpost',
            name='image',
            field=models.ImageField(blank=True, upload_to='posts', verbose_name=' '),
        ),
    ]
