# Generated by Django 2.0.2 on 2018-04-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20180413_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpost',
            name='autor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='createpost',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='createpost',
            name='text',
            field=models.TextField(),
        ),
    ]
