# Generated by Django 2.0.2 on 2018-04-13 19:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_auto_20180413_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpost',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
