# Generated by Django 2.0.2 on 2018-04-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_auto_20180414_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpost',
            name='image',
            field=models.ImageField(blank=True, upload_to='posts', verbose_name=False),
        ),
    ]
